### ISSUE TITLE
Getting build errors using Ti SDK 6.0.3

### ISSUE THREAD

**Issue by alphakilo45** [testfairy/ti.testfairy#8]
When I attempt to run install.sh and then attempt to package the Android Module, I get build errors (attached)
[build_error.txt](https://github.com/testfairy/ti.testfairy/files/923996/build_error.txt)

**Comment by vijaysharm** [comment]
Hi @alphakilo45, you might be missing some environment variables. See how we setup our environment in the `.travis` file. You can also download v2.1.1 from the releases page here
https://github.com/testfairy/ti.testfairy/releases/tag/2.1.1
